version: "3.7"
services:

  serv-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectomineriasegura
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:

      - 3306:3306
    volumes:
      - ./:/var/lib/mysql
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.100.9


  serv-laravel:
    
    build:

      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - ./proyectoMineriaSegura:/var/www/
      - ./proyectoMineriaSegura/public:/var/www/html
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.100.10

    depends_on:
      - serv-mysql


volumes:
  proyectomineriasegura: 
  database:     
networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 173.22.100.0/24